import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
// import Landing1 from "@/components/Landing1";
// import Content from "@/components/Content";
// import Extension from "@/components/Extension";
// import Customise from "@/components/Customise";
// import Card from "@/components/Card";
// import Work from "@/components/Work";
// import Data from "@/components/Data";
// import Sponsors from "@/components/Sponsors";
// import App from "next/app";
// import White from "@/components/White";
// import Footer from "@/components/Footer";
// import Footer1 from "@/components/Footer1";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        {/* <Landing1 />
        <Content />
        <Extension />
        <Customise />
        <Card />
        <Work />
        <Data />
        <Sponsors />
        <White />
        <Footer />
        <Footer1 /> */}
      </body>
    </html>
  );
}
